openapi: 3.0.0
info:
  title: Chat App
  description: API
  version: 0.1.9

servers:
  - url: http://localhost:4444/api
    description: production server
  - url: http://localhost:4444/api
    description: local server
paths:
